Repository iamprovidence/Platform_Of_Corporate_Information_Systems, pull requests merged in 2018-11, with the labels that each got.

#106 Feature/squash binding
  Task3/Project/Task3/Forms/CabinetWindow.xaml
  Task3/Project/Task3/Forms/LogInWindow.xaml
  Task3/Project/Task3/Forms/MainWindow.xaml
  Task3/Project/Task3/Forms/ProgressWindow.xaml
  Task3/Project/Task3/Theme/GoldenShower.xaml
Labels: aim

#113 Fix/bug fixing
  Task3/Project/DataControl/Interfaces/IDataAccessService.cs
  Task3/Project/DataControl/Services/CsvFileService.cs
  Task3/Project/DataControl/ViewModel/ApplicationViewModel.cs
  Task3/Project/TaxiDriver/Struct/Сhampion.cs
  Task3/Project/TaxiDriver/_dll/TaxiDriver.dll
  Task3/Project/Test/ChampionTest.cs
Labels: bug

#116 Squash/view
  Task3/Project/DataControl/Services/CsvFileService.cs
  Task3/Project/Task3/Forms/CabinetWindow.xaml
  Task3/Project/Task3/Forms/LogInWindow.xaml
  Task3/Project/Task3/Forms/MainWindow.xaml
  Task3/Project/Task3/Forms/ScoreWindow.xaml
  Task3/Project/Task3/Theme/GoldenShower.xaml
Labels: bug

#117 fix/ViewFix (#116)
  Task3/Project/DataControl/Services/CsvFileService.cs
  Task3/Project/Task3/Forms/CabinetWindow.xaml
  Task3/Project/Task3/Forms/LogInWindow.xaml
  Task3/Project/Task3/Forms/MainWindow.xaml
  Task3/Project/Task3/Forms/ScoreWindow.xaml
  Task3/Project/Task3/Theme/GoldenShower.xaml
Labels: aim

#119 Sqush/view
  Task3/Project/Task3/Forms/MainWindow.xaml
  Task3/Project/Task3/Forms/MessageBoxWindow.xaml
  Task3/Project/Task3/Forms/MessageBoxWindow.xaml.cs
  Task3/Project/Task3/Theme/GoldenShower.xaml
Labels: invalid

#120 Features/view model
  Task3/Project/DataControl/ViewModel/ApplicationViewModel.cs
Labels: aim

#129 Task4/prepare
  Images/Task4/ico.png
  Task4/Project/Task4/Task4/Task4.csproj
  Task4/Project/Task4/Task4/database.ico
  Task4/README.md
Labels: aim

#130 Queries 11-20
  Task4/Project/Task4/Task4/Program.cs
Labels: aim

#133 feature/3.6
  Task4/Project/Task4/Task4/Program.cs
Labels: aim

#132 Querys update
  Task4/Project/Task4/Task4/Program.cs
Labels: aim

#135 Feature/help
  Task4/Project/Task4/Task4/Program.cs
Labels: aim, invalid

#136 Update Program.cs
  Task4/Project/Task4/Task4/Program.cs
Labels: aim

#137 Task4/finish
  README.md
  Task4/Project/Task4/Task4/Program.cs
  Task4/README.md
Labels: aim

#151 Features/uc gr uow
  Task5/Project/TaxiDriver/Context/DriverContext.cs
  Task5/Project/TaxiDriver/Interfaces/IGenericRepository.cs
  Task5/Project/TaxiDriver/Interfaces/IUnitOfWork.cs
  Task5/Project/TaxiDriver/Services/GenericRepository.cs
  Task5/Project/TaxiDriver/Services/UnitOfWork.cs
Labels: aim
